### ISSUE TITLE
Python3.8下安装pyminifier失败

### ISSUE THREAD

**Issue by ZhaoQi99** [ZhaoQi99/pyencrypt-pye#28]
似乎有一个新库 https://pypi.org/project/pyminifier3/, 不确定能否解决问题

Related to #18

**Comment by lovechang1986** [comment]
在安装pyminifier时各种出错，但是安装pyminifier3ok，请问目前更新依赖到pyminifier3了吗？

**Comment by ZhaoQi99** [comment]
> 在安装pyminifier时各种出错，但是安装pyminifier3ok，请问目前更新依赖到pyminifier3了吗？

Hi! 暂时还没有,我这周有空试试😊

**Comment by ZhaoQi99** [comment]
> 在安装pyminifier时各种出错，但是安装pyminifier3ok，请问目前更新依赖到pyminifier3了吗？

刚刚Release了v0.2.0版本,你试试呢😊
