### ISSUE TITLE
pyencrypt cli --with-license option not passed on

### ISSUE THREAD

**Issue by agpf** [ZhaoQi99/pyencrypt-pye#30]
看起来 with-license 参数没有传递到 generate_so_file ，导致：--width-license 失效。

我简单添加了一下，
`encrypt_command::generate_so_file(..., license=with_license)`

简单从测试了一下，通过

**Comment by ZhaoQi99** [comment]
> 看起来 with-license 参数没有传递到 generate_so_file ，导致：--width-license 失效。
> 
> 我简单添加了一下， `encrypt_command::generate_so_file(..., license=with_license)`
> 
> 简单从测试了一下，通过

`generate_so_file(cipher_key, d, n, license=with_license) `忘了传参了😂
https://github.com/ZhaoQi99/pyencrypt-pye/blob/4b87b3f2e39f537058cdb9ab759214956a25ae27/pyencrypt/cli.py#L188-L192

**Comment by ZhaoQi99** [comment]
> 看起来 with-license 参数没有传递到 generate_so_file ，导致：--width-license 失效。
> 
> 我简单添加了一下， `encrypt_command::generate_so_file(..., license=with_license)`
> 
> 简单从测试了一下，通过

Release 了 `v0.2.1`,你试试
